const state={type:'normal',threads:12,rows:14,pattern:'diamonds',showRows:true,showLetters:true,wide:false,scale:1,weave:false,next:0,done:new Set(),colors:['#74d9bd','#0f7778','#fff3c9','#dd006d','#7b3fa0','#171717','#b3b6bb','#ee8fbc','#0eaab6','#9d91df','#0968bf','#ffffff']};
const $=s=>document.querySelector(s);const svg=$('#patternSvg'),canvas=$('#braceletCanvas'),ctx=canvas.getContext('2d');
if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
function saveLocal(){localStorage.setItem('braceletStudioByCalie',JSON.stringify({...state,done:[...state.done]}))}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem('braceletStudioByCalie'));if(s){Object.assign(state,s);state.done=new Set(s.done||[])}}catch{}}
function letter(i){let s='';do{s=String.fromCharCode(65+i%26)+s;i=Math.floor(i/26)-1}while(i>=0);return s}
function luminance(hex){const n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return(r*299+g*587+b*114)/1000}
function knotFor(r,c){const sum=r+c;if(state.pattern==='chevrons')return c<state.threads/2?'f':'b';if(state.pattern==='stripes')return r%2?'b':'f';if(state.pattern==='hearts')return (Math.abs(c-state.threads/2)<2&&r%6<3)?'fb':(sum%2?'f':'b');return ['f','b','fb','bf'][(Math.floor(c/2)+r)%4]}
function colorFor(r,c){if(state.type==='alpha'){return (r+c)%5===0?state.colors[3]:(r%4<2?state.colors[2]:state.colors[1])} if(state.pattern==='diamonds'){const mid=(state.threads-1)/2;const d=Math.abs((c-mid)+(r%6-3));return state.colors[Math.floor(d)%state.colors.length]}return state.colors[(c+r)%state.colors.length]}
function renderPalette(){const p=$('#palette');p.innerHTML='';state.colors.forEach((col,i)=>{const b=document.createElement('button');b.className='swatch';b.style.background=col;b.title='Couleur '+(i+1);b.onclick=()=>{$('#colorPicker').value=col;$('#colorPicker').oninput=e=>{state.colors[i]=e.target.value;renderAll()};$('#colorPicker').click()};p.appendChild(b)})}
function renderPreview(){const rect=canvas.getBoundingClientRect();canvas.width=Math.max(900,rect.width*devicePixelRatio);canvas.height=96*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);const w=rect.width,h=96,step=22;ctx.save();ctx.beginPath();roundRect(ctx,0,9,w,78,12);ctx.clip();for(let x=-step;x<w+step;x+=step){for(let y=0;y<4;y++){const col=state.colors[(Math.floor(x/step)+y)%state.colors.length];ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(x+y*2,9);ctx.lineTo(x+step/2+y*2,48);ctx.lineTo(x+y*2,87);ctx.lineTo(x-step/2+y*2,48);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(0,0,0,.08)';ctx.stroke()}}ctx.restore();ctx.strokeStyle='#dbe3f0';ctx.lineWidth=1;roundRect(ctx,0,9,w,78,12);ctx.stroke()}
function roundRect(c,x,y,w,h,r){c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r)}
function renderPattern(){const gapX=82,gapY=66,marginL=92,marginT=72;const w=marginL+state.threads*gapX+70,h=marginT+state.rows*gapY+80;svg.setAttribute('width',w*state.scale);svg.setAttribute('height',h*state.scale);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.style.transform=`scale(${state.scale})`;svg.innerHTML='';if(state.showLetters){for(let c=0;c<state.threads;c++)text(letter(c),marginL+c*gapX,38,'axisText')}if(state.showRows){for(let r=0;r<state.rows;r++)text(r+1,48,marginT+r*gapY+6,'rowText')}
for(let r=0;r<state.rows;r++){for(let c=0;c<state.threads;c++){const x=marginL+c*gapX,y=marginT+r*gapY;drawThreads(r,c,x,y,gapX,gapY)}}
let idx=0;for(let r=0;r<state.rows;r++){for(let c=0;c<state.threads;c++){const x=marginL+c*gapX,y=marginT+r*gapY;drawNode(r,c,x,y,idx++)}}}
function line(x1,y1,x2,y2,col,width=13){const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);l.setAttribute('stroke',col);l.setAttribute('stroke-width',width);l.setAttribute('class','threadLine');svg.appendChild(l)}
function drawThreads(r,c,x,y,gx,gy){const c1=colorFor(r,c),c2=colorFor(r,c+1);const k=knotFor(r,c);if(k==='f'||k==='fb'){line(x-22,y-33,x+22,y+33,c1);line(x+22,y-33,x-22,y+33,c2,9)}else{line(x+22,y-33,x-22,y+33,c2);line(x-22,y-33,x+22,y+33,c1,9)}}
function drawNode(r,c,x,y,idx){const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','node');if(state.done.has(idx))g.classList.add('done');if(state.weave&&idx===state.next)g.classList.add('next');g.dataset.idx=idx;const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',x);circle.setAttribute('cy',y);circle.setAttribute('r',25);const fill=colorFor(r,c);circle.setAttribute('fill',fill);circle.setAttribute('stroke','#111');circle.setAttribute('stroke-width','1.5');g.appendChild(circle);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',x);t.setAttribute('y',y+1);t.setAttribute('class','knotText '+(luminance(fill)>185?'dark':''));t.textContent={f:'↘',b:'↙',fb:'↘↙',bf:'↙↘'}[knotFor(r,c)];g.appendChild(t);g.onclick=()=>{if(state.weave){state.done.add(idx);while(state.done.has(state.next)&&state.next<state.rows*state.threads)state.next++;saveLocal();renderPattern()}};svg.appendChild(g)}
function text(content,x,y,cls){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.textContent=content;t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('class',cls);svg.appendChild(t)}
function renderInfo(){const type=state.type==='alpha'?'Alpha':'Normal';$('#threadsValue').textContent=state.threads;$('#rowsInput').value=state.rows;$('#patternSelect').value=state.pattern;$('#showRows').checked=state.showRows;$('#showLetters').checked=state.showLetters;$('#wideMode').checked=state.wide;$('#statusText').textContent=`${type} · ${$('#patternSelect').selectedOptions[0].textContent}`;$('#infoBox').innerHTML=`Fils : <b>${state.threads}</b><br>Rangées : <b>${state.rows}</b><br>Type : <b>${type}</b><br>Motif : <b>${$('#patternSelect').selectedOptions[0].textContent}</b><br>Nœuds : <b>${state.threads*state.rows}</b>`;document.querySelectorAll('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.type===state.type));$('#patternScroller').style.minHeight=state.wide?'720px':'520px'}
function renderAll(){renderInfo();renderPalette();renderPreview();renderPattern();saveLocal()}
loadLocal();renderAll();addEventListener('resize',renderPreview);
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;renderAll()});$('#minusThreads').onclick=()=>{state.threads=Math.max(4,state.threads-2);renderAll()};$('#plusThreads').onclick=()=>{state.threads=Math.min(40,state.threads+2);renderAll()};$('#rowsInput').onchange=e=>{state.rows=Math.max(4,Math.min(80,+e.target.value||14));renderAll()};$('#patternSelect').onchange=e=>{state.pattern=e.target.value;renderAll()};$('#showRows').onchange=e=>{state.showRows=e.target.checked;renderAll()};$('#showLetters').onchange=e=>{state.showLetters=e.target.checked;renderAll()};$('#wideMode').onchange=e=>{state.wide=e.target.checked;renderAll()};$('#newBtn').onclick=()=>{if(confirm('Créer un nouveau patron ?')){state.done.clear();state.next=0;renderAll()}};$('#saveBtn').onclick=()=>{saveLocal();alert('Projet sauvegardé sur cet iPad.')};$('#weaveBtn').onclick=()=>{state.weave=!state.weave;$('#weaveBtn').textContent=state.weave?'Quitter tissage':'Mode tissage';renderAll()};$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.download='bracelet-studio-by-calie.png';a.href=canvas.toDataURL('image/png');a.click()};
let lastDist=0;$('#patternScroller').addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const dx=e.touches[0].clientX-e.touches[1].clientX,dy=e.touches[0].clientY-e.touches[1].clientY,d=Math.hypot(dx,dy);if(lastDist){state.scale=Math.max(.65,Math.min(1.8,state.scale+(d-lastDist)/500));renderPattern()}lastDist=d}},{passive:false});$('#patternScroller').addEventListener('touchend',()=>{lastDist=0;saveLocal()});
