const colors=['#74dbc2','#0f7478','#fff2c8','#df006c','#7b3fb0','#171717','#b6bbc2','#f08ab8','#09aeba','#9b8add','#0d68bd','#ffffff'];
let state={threads:12,rows:12,type:'normal',pattern:'diamonds',alphaText:'CALIE',colors,selectedColor:0,weave:false,done:new Set(),scale:1};
const $=id=>document.getElementById(id); const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
function save(){localStorage.setItem('braceletStudioCalieV3',JSON.stringify({...state,done:[...state.done]}));}
function load(){try{let s=JSON.parse(localStorage.getItem('braceletStudioCalieV3')); if(s){state={...state,...s,done:new Set(s.done||[])}}}catch(e){}}
function knotType(r,c){ if(state.pattern==='chevrons') return c<state.threads/2?'↘':'↙'; if(state.pattern==='waves') return ['↘','↙','↘↙','↙↘'][(r+c)%4]; if(state.pattern==='hearts') return (r%4<2)?(c%3?'↙':'↘↙'):(c%3?'↘':'↙↘'); return ['↘','↙','↘↙','↙↘'][(Math.floor(c/2)+r)%4]; }
function colorFor(r,c){ if(state.type==='alpha'){ const text=state.alphaText.toUpperCase(); const hit=text.charCodeAt((c+r)%Math.max(1,text.length))%5===0; return hit?state.colors[3]:state.colors[(c+r)%state.colors.length]; } return state.colors[(c+r)%state.colors.length]; }
function renderPalette(){ const p=$('palette'); p.innerHTML=''; state.colors.forEach((col,i)=>{let b=document.createElement('button'); b.className='swatch '+(i===state.selectedColor?'active':''); b.style.background=col; b.title='Couleur '+(i+1); b.onclick=()=>{state.selectedColor=i; $('colorPicker').value=col; $('colorPicker').click(); renderPalette();}; p.appendChild(b);});}
function drawPreview(){ const canvas=$('braceletPreview'), ctx=canvas.getContext('2d'); const w=canvas.width=canvas.offsetWidth*devicePixelRatio, h=canvas.height=84*devicePixelRatio; ctx.scale(devicePixelRatio,devicePixelRatio); ctx.clearRect(0,0,w,h); const cw=canvas.offsetWidth, ch=84, size=22; for(let x=-size;x<cw+size;x+=size*.9){ let i=Math.floor((x+size)/(size*.9)); ctx.fillStyle=state.colors[i%state.colors.length]; ctx.beginPath(); ctx.moveTo(x,8); ctx.lineTo(x+size/2,ch/2); ctx.lineTo(x,ch-8); ctx.lineTo(x-size/2,ch/2); ctx.closePath(); ctx.fill(); if(state.realistic){ctx.strokeStyle='rgba(0,0,0,.12)'; ctx.stroke(); ctx.globalAlpha=.18; ctx.fillStyle='#000'; ctx.fillRect(x-1,10,2,ch-20); ctx.globalAlpha=1;} } }
function renderPattern(){ const svg=$('patternSvg'), wrap=$('patternWrap'); const gapX=74,gapY=62, left=82, top=64, radius=22, W=left*2+(state.threads-1)*gapX, H=top*2+(state.rows-1)*gapY; svg.setAttribute('width',W*state.scale); svg.setAttribute('height',H*state.scale); svg.setAttribute('viewBox',`0 0 ${W} ${H}`); svg.style.transform=`scale(${state.scale})`; svg.innerHTML='';
 const ns='http://www.w3.org/2000/svg'; const add=(tag,attrs,parent=svg)=>{let e=document.createElementNS(ns,tag); Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v)); parent.appendChild(e); return e;};
 if($('showLetters').checked){for(let c=0;c<state.threads;c++){add('text',{x:left+c*gapX,y:28,'text-anchor':'middle',class:'letterLabel'}).textContent=letters[c%26];}}
 if($('showRows').checked){for(let r=0;r<state.rows;r++){add('text',{x:30,y:top+r*gapY+7,'text-anchor':'middle',class:'rowLabel'}).textContent=r+1;}}
 for(let r=0;r<state.rows;r++){for(let c=0;c<state.threads-1;c++){let x1=left+c*gapX,y1=top+r*gapY,x2=left+(c+1)*gapX,y2=top+(r+1)*gapY; if(r<state.rows-1){add('line',{x1,y1,x2,y2,stroke:colorFor(r,c),'stroke-width':14,class:'threadLine'}); add('line',{x1:x2,y1,x2:left+c*gapX,y2,stroke:colorFor(r,c+1),'stroke-width':14,class:'threadLine'});}}}
 for(let r=0;r<state.rows;r++){for(let c=0;c<state.threads;c++){let key=r+'-'+c, x=left+c*gapX, y=top+r*gapY; let g=add('g',{class:'knot '+(state.done.has(key)?'done':'')+(nextKey()===key?' next':'')}); g.dataset.key=key; add('circle',{cx:x,cy:y,r:radius,fill:colorFor(r,c),stroke:'#111','stroke-width':1.5},g); add('text',{x,y:y+7,'text-anchor':'middle','font-size':25,fill:isDark(colorFor(r,c))?'white':'#111'},g).textContent=knotType(r,c); g.onclick=()=>{ if(state.weave){state.done.add(key); save(); renderPattern();} };}}
}
function nextKey(){ for(let r=0;r<state.rows;r++)for(let c=0;c<state.threads;c++){let k=r+'-'+c;if(!state.done.has(k))return k;} return '';}
function isDark(hex){let c=hex.replace('#','');let r=parseInt(c.substr(0,2),16),g=parseInt(c.substr(2,2),16),b=parseInt(c.substr(4,2),16);return (r*299+g*587+b*114)/1000<140;}
function update(){ $('threadCount').textContent=state.threads; $('rows').value=state.rows; $('type').value=state.type; $('pattern').value=state.pattern; $('alphaText').value=state.alphaText; $('alphaBox').classList.toggle('hidden',state.type!=='alpha'); $('weaveBtn').textContent=state.weave?'Tissage activé':'Mode tissage'; renderPalette(); drawPreview(); renderPattern(); save(); }
$('minus').onclick=()=>{state.threads=Math.max(4,state.threads-2);update()}; $('plus').onclick=()=>{state.threads=Math.min(40,state.threads+2);update()};
['rows','type','pattern','alphaText','showRows','showLetters','realistic'].forEach(id=>$(id).oninput=()=>{state.rows=+$('rows').value;state.type=$('type').value;state.pattern=$('pattern').value;state.alphaText=$('alphaText').value;state.realistic=$('realistic').checked;update();});
$('colorPicker').oninput=e=>{state.colors[state.selectedColor]=e.target.value;update();}; $('weaveBtn').onclick=()=>{state.weave=!state.weave;update();}; $('resetProgress').onclick=()=>{state.done.clear();update();}; $('newBtn').onclick=()=>{if(confirm('Créer un nouveau bracelet ?')){localStorage.removeItem('braceletStudioCalieV3');location.reload();}}; $('saveBtn').onclick=()=>{save();alert('Projet sauvegardé sur cet iPad.');}; $('exportBtn').onclick=()=>{const a=document.createElement('a');a.download='bracelet-studio-by-calie.png';a.href=$('braceletPreview').toDataURL('image/png');a.click();};
let lastDist=0; $('patternWrap').addEventListener('touchmove',e=>{ if(e.touches.length===2){e.preventDefault(); let [a,b]=e.touches; let d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY); if(lastDist){state.scale=Math.min(2.2,Math.max(.65,state.scale+(d-lastDist)/500)); renderPattern();} lastDist=d;} },{passive:false}); $('patternWrap').addEventListener('touchend',()=>lastDist=0);
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js'); load(); update();
